openapi: 3.0.2
info:
  title: "Card Payment API"
  version: "1.0.00"
  description: |
    # Overview
    This interface must be implemented to accepts and send Iso20022 financial transactions to and from TJ.
    
  contact:
    name: Transaction Junction
    url: 'http://www.transactionjunction.co.za'
    email: cardpaymnetapi-integration@switch.tj
security: 
  - ApiKey: []
paths:
  /v1/AcceptorAuthorisation:
    post:
      summary: The AcceptorAuthorisationRequest message is sent by an acceptor (or its agent) to the acquirer (or its agent), to check with the issuer (or its agent) that the account associated to the card has the resources to fund the payment. This checking will include validation of the card data and any additional transaction data provided.
      operationId: authorisation
      requestBody:
        required: true
        content:
          application/json:   
            schema:
             $ref: '#/components/schemas/AcceptorAuthoisationRequestV09'
          application/xml:
            schema:
             $ref: '#/components/schemas/AcceptorAuthoisationRequestV09'
          
      responses:
        '200':
          description: Transaction Reversal
          content:
            application/json:   
              schema:
                $ref: '#/components/schemas/AcceptorAuthorisationResponseV09'
            application/xml:   
              schema:
                $ref: '#/components/schemas/AcceptorAuthorisationResponseV09'
        default:
          description: Error information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptorAuthorisationResponseV09'
                
components:
  schemas:
    AcceptorAuthoisationRequestV09:
      type: object
      properties: 
        header:
          $ref: '#/components/schemas/Header'
        authorisationRequest:
          $ref: '#/components/schemas/AuthorisationRequest'
        securityTrailer:
          $ref: '#/components/schemas/SecurityTrailer'
    AcceptorAuthorisationResponseV09:
      type: object
      properties:
        header:
          $ref: '#/components/schemas/Header'
        authoirsationResponse:
          $ref: '#/components/schemas/AuthorisationResponse'
        securityTrailer:
          $ref: '#/components/schemas/SecurityTrailer'
    Header:
      type: string
    AuthorisationRequest:
      type: string
    AuthorisationResponse:
      type: string
    SecurityTrailer:
      type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
      description: The API key value will be provided by Transaction Junction. It should be provided in the header X-Api-Key.